version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    platform: linux/arm64/v8
    container_name: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nestjs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: